### ISSUE TITLE
Design message hierarchies

### ISSUE THREAD

**Issue by dexmona** [legokor/UniversalGnd#1]
- [x] Decide on the structure of the message hierarchies
- [x] Define messages sent by the server for UPRA
- [ ] Define messages sent by the server for MAM
- [ ] Define messages sent by the server for QC
- [x] Define messages sent by the client for UPRA
- [ ] Define messages sent by the client for MAM
- [ ] Define messages sent by the client for QC

All defined message types should be documented in the [Message type catalog](https://github.com/legokor/UniversalGnd/wiki/Message-type-catalog). See also this document for the current state of planning.
