### ISSUE TITLE
Design and implement logging

### ISSUE THREAD

**Issue by dexmona** [legokor/UniversalGnd#7]
Incoming messages should be logged, ideally in every stage from them getting received as packets from the modem (in case of UPRA) to them arriving as messages to the clients.

### Decide
- [ ] What to log
- [ ] When to log
- [ ] Where to store the logs created

### Implement
- [ ] Server side logging
- [ ] Cilent side logging (lower priority)
